### PR TITLE
Feature/sd 8224 add type and classifier

### PR DESCRIPTION
**Pull request by zonArt**

### CODE REVIEW

**Comment by pskumar448** [comment]
@zonArt 
Thanks for contributing and adding new feature.

**Comment by zonArt** [comment]
No problem, thanks for this plugin. Do you plan to release a new version of it ?

**Comment by pskumar448** [comment]
@zonArt 
Yes this Saturday planning to release a new version along with another issue fix.

**Comment by pskumar448** [comment]
@zonArt 
Today morning 2.4 version released with these changes.

**Pull request merged**
