### PR TITLE
True multiple artifacts upload

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by michaelboyles** [comment]
@pskumar448 Anything stopping this from being merged and released? Having multiple folders in Nexus for a pom and jar is confusing. I believe this would fix that, correct?

**Comment by pskumar448** [comment]
I will Verify and Let you know the feedback.

**Comment by pskumar448** [comment]
@diorcety 
This PR is mainly a Code Quality related. Or Any fix done with regards to Multiple Artifacts uploading functionality.

**Comment by michaelboyles** [comment]
@pskumar448 When uploading multiple artifacts, such as

```
nexusArtifactUploader(
    artifacts: [
        [artifactId: 'my-lib', file: 'pom.xml', type: 'pom']
        [artifactId: 'my-lib', file: 'target/my-lib.jar', type: 'jar']
    ],
    groupId: 'foo',
    version: '2.0.0',
    ...
)
```

Then the result is this:

S0dTa

They should ideally come under the same folder (but in practice, it does not make any difference for dependent projects). 

By making one `DeployRequest` containing all artifacts, rather than one `DeployRequest` each artifact, I think it should fix the above problem.

**Comment by diorcety** [comment]
@pskumar448 It adds a true multiple artifacts support. I'm currently using it in production.

**Comment by diorcety** [comment]
#18  should be valided first

**Comment by michaelboyles** [comment]
@pskumar448 Thank you for merging. Any plans for when the next release will be?

**Comment by pskumar448** [comment]
Coming Sunday.

**Comment by michaelboyles** [comment]
Tested and confirmed the fix is working correctly. Thank you both for your efforts

**Comment by igcherkaev** [comment]
Hi all. We suspect this PR broke parameters evaulation provided via GUI job configuration. With 2.10 it was working just fine, upgraded to 2.12, it's broken now.

We've had it like this all the time and it used to work just fine:

image

Now with 2.12 it generates a wrong nexus URL and artifactId:

```
Uploading artifact ycs-core-0.4.108.title.gem started....
GroupId: gems
ArtifactId: gems
Classifier: 
Type: gem
Version: 0.4.108.title
File: ycs-core-0.4.108.title.gem
Repository:ycs-gems-internal
Uploading: http://[redacted]/repository/ycs-gems-internal/gems/${GEM}/0.4.108.title/${GEM}-0.4.108.title.gem
10 % completed (12 kB / 122 kB).
20 % completed (25 kB / 122 kB).
30 % completed (37 kB / 122 kB).
40 % completed (49 kB / 122 kB).
50 % completed (61 kB / 122 kB).
60 % completed (74 kB / 122 kB).
70 % completed (86 kB / 122 kB).
80 % completed (98 kB / 122 kB).
90 % completed (111 kB / 122 kB).
100 % completed (122 kB / 122 kB).
Failed to deploy artifacts: Could not transfer artifact gems:${GEM}:gem:0.4.108.title from/to ycs-gems-internal (http://[redacted]/repository/ycs-gems-internal): Failed to transfer file: http://[redacted]/repository/ycs-gems-internal/gems/%24%7BGEM%7D/0.4.108.title/%24%7BGEM%7D-0.4.108.title.gem. Return code is: 500, ReasonPhrase:Server Error.
```

Notice how ${GEM} is literally used without taking its value. Downgrading to 2.10 without making any changes to the job's configuration restored the previous and correct behavior. The GEM parameters is passed as a string when we start the job with the "Build Now with parameters" button.

I don't see "Issues" tab for this project where I could open one, so I am posting it here, since it looks like it was this PR that potentially broke the previous behavior.

Thank you!

**Comment by michaelboyles** [comment]
You're right. It seems some of the values were previously wrapped in calls to `envVars.expand()` and no longer are. It can be seen [here](https://github.com/jenkinsci/nexus-artifact-uploader-plugin/pull/16/commits/96f8189808f723d636a50e4562d640b1171ae2ac#diff-39868400635bb52962c5c2dbb563c627R240)

I will fix it. I will submit a PR tomorrow.

**Comment by igcherkaev** [comment]
Thank you @michaelboyles for quick turnaround! Much appreciated here!

**Comment by diorcety** [comment]
Sorry for all the issue created by this PR 😞

**Pull request merged**
